# Generated by Django 5.1.1 on 2024-09-18 23:24

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('data_server', '0001_initial'), ('data_server', '0002_remove_appointment_doctor_patient_and_more'), ('data_server', '0003_alter_clinic_affliated_doctors_and_more'), ('data_server', '0004_patient_address')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npi', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('specialities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('CL', 'Cleaning'), ('CR', 'Crown'), ('FI', 'Filling'), ('RC', 'Root Canal'), ('WH', 'Whitening')], max_length=2), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ClinicDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(max_length=100)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_server.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_server.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('procedure', models.CharField(choices=[('CL', 'Cleaning'), ('CR', 'Crown'), ('FI', 'Filling'), ('RC', 'Root Canal'), ('WH', 'Whitening')], max_length=2)),
                ('clinic', models.ForeignKey(default=40, on_delete=django.db.models.deletion.CASCADE, to='data_server.clinic')),
                ('doctor', models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='data_server.doctor')),
                ('patient', models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='data_server.patient')),
            ],
        ),
        migrations.AddField(
            model_name='clinic',
            name='affliated_doctors',
            field=models.ManyToManyField(blank=True, through='data_server.ClinicDoctor', to='data_server.doctor'),
        ),
        migrations.AddField(
            model_name='patient',
            name='affliated_clinics',
            field=models.ManyToManyField(blank=True, to='data_server.clinic'),
        ),
        migrations.AddField(
            model_name='patient',
            name='afflicated_doctors',
            field=models.ManyToManyField(blank=True, to='data_server.doctor'),
        ),
        migrations.AddField(
            model_name='patient',
            name='ssn',
            field=models.CharField(default=123456789, max_length=9),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('procedures', models.CharField(choices=[('CL', 'Cleaning'), ('CR', 'Crown'), ('FI', 'Filling'), ('RC', 'Root Canal'), ('WH', 'Whitening')], max_length=2)),
                ('note', models.TextField()),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_server.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_server.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_server.patient')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
