# Generated by Django 5.1.1 on 2024-09-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_server', '0005_doctor_email_doctor_phone_alter_appointment_clinic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='address',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
