# Generated by Django 5.1.1 on 2024-09-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_server', '0006_clinic_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
