# Generated by Django 5.1.1 on 2024-09-19 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_server', '0007_patient_gender_alter_patient_ssn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='specialities',
            new_name='specialties',
        ),
    ]
