# Generated by Django 5.1.1 on 2024-09-19 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_server', '0008_rename_specialities_doctor_specialties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
    ]
