# Generated by Django 5.1.1 on 2024-09-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_server', '0009_remove_patient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
