# Generated by Django 5.1.1 on 2024-09-20 06:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_server', '0010_clinic_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date_booked',
            field=models.DateField(auto_now_add=True, default="2024-09-20"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visit',
            name='procedures',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('CL', 'Cleaning'), ('CR', 'Crown'), ('FI', 'Filling'), ('RC', 'Root Canal'), ('WH', 'Whitening')], max_length=2), size=None),
        ),
    ]
