# Generated by Django 5.1.1 on 2024-09-21 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_server', '0012_rename_time_appointment_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorschedule',
            name='day',
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='date',
            field=models.DateField(default="2024-09-21"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workingschedule',
            name='doctor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='data_server.doctor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workingschedule',
            name='day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
    ]
