# Generated by Django 5.1.1 on 2024-09-21 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_server', '0014_remove_workingschedule_doctor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clinicdoctor',
            unique_together={('clinic', 'doctor')},
        ),
    ]
