# Generated by Django 5.1.1 on 2024-09-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_server', '0015_alter_clinicdoctor_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='visit',
            name='start_time',
            field=models.TimeField(default='0:00'),
            preserve_default=False,
        ),
    ]
